### ISSUE TITLE
Question re: ol and ul

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/list-groups#1]
I'm a bit confused with what Markbot is expecting here: `ol > li > ul` and `ol > li > ul > li` 

I've never seen a list structure like this and even thought `ol`and `ul` could not be each other's children.

Could you please clarify? Thanks.

@thomasjbradley

**Comment by thomasjbradley** [comment]
You can definitely nest lists! But—the inner list must be inside the `<li>`:

```html
<ol>
  <li>
    <ul>
      <li></li>
    </ul>
  </li>
</ol>
```
```
